[package]
name = "ethereum-proofs"
version = "0.1.0"
edition = "2021"

[dependencies]
hex-literal = { version = "0.4.1", default-features = false }
evm = { version = "0.39.1", default-features = false, features = [
  "with-serde",
] }
primitive-types = { version = "0.12.0", default-features = false }
rlp = { version = "0.5.2", default-features = false }
trie-db = { version = "0.27.1", default-features = false }
hash-db = { version = "0.16.0", default-features = false }
sha3 = { version = "0.10", default-features = false }
tiny-keccak = { version = "2.0.0", default-features = false, features = [
  "keccak",
] }
alloy-primitives = { version = "0.4.1", default-features = false }
alloy-rlp = { version = "0.3.3", default-features = false }

[features]
default = ["std"]
std = ["trie-db/std", "hash-db/std", "rlp/std"]
